version: '3.5'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ROOT_USER: guest
      MINIO_ROOT_PASSWORD: guest123
    command: server --console-address ":9001" /data
    restart: unless-stopped
    networks:
      - default
        
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
    restart: unless-stopped

volumes:
  minio_storage: {}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.3.0/24